CREATE PROCEDURE AddGerente
	@NOME VARCHAR(100)
	,@RG CHAR(9)
	,@CPF CHAR(11)
AS
BEGIN
	INSERT INTO TESTE(NOME,RG,CPF)
	VALUES (@NOME,@RG,@CPF)
END

CREATE PROCEDURE ListarGerente
AS
BEGIN
	SELECT * FROM GERENTE_EMPRESA
END

EXEC ListarGerente